# Prefers double quote
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  EnforcedStyle: always
  Exclude:
    - "Gemfile"
    - "Rakefile"
    - "bin/*"
    - "buda.gemspec"
